source 'https://rubygems.org'

gem 'maxminddb'
gem 'ipaddress'
gem 'ip2location_ruby', '~> 7.0'
gem 'ip2proxy_ruby', '~> 1.0', '>= 1.0.2'
gem 'rubyzip'
gem 'slop'
gem 'ruby-progressbar'
gem 'chunky_png'